/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans: ["'Stardom Regular'", "'Geist'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "sans-serif"],
      display: ["'Instrument Serif'", "ui-serif", "Georgia", "serif"],
    },
    colors: {
      background: 'var(--background)',
      foreground: 'var(--foreground)',
      card: 'var(--card)',
      'card-foreground': 'var(--card-foreground)',
      popover: 'var(--popover)',
      'popover-foreground': 'var(--popover-foreground)',
      primary: 'var(--primary)',
      'primary-foreground': 'var(--primary-foreground)',
      secondary: 'var(--secondary)',
      'secondary-foreground': 'var(--secondary-foreground)',
      muted: 'var(--muted)',
      'muted-foreground': 'var(--muted-foreground)',
      accent: 'var(--accent)',
      'accent-foreground': 'var(--accent-foreground)',
      destructive: 'var(--destructive)',
      'destructive-foreground': 'var(--destructive-foreground)',
      border: 'var(--border)',
      input: 'var(--input)',
      ring: 'var(--ring)',
      surface: 'var(--surface)',
      'surface-elevated': 'var(--surface-elevated)',
      'on-surface': 'var(--on-surface)',
      'on-surface-variant': 'var(--on-surface-variant)',
      'surface-container-low': 'var(--surface-container-low)',
      'surface-container-lowest': 'var(--surface-container-lowest)',
      'surface-container-high': 'var(--surface-container-high)',
      'outline-variant': 'var(--outline-variant)',
      chart: {
        1: 'var(--chart-1)',
        2: 'var(--chart-2)',
        3: 'var(--chart-3)',
        4: 'var(--chart-4)',
        5: 'var(--chart-5)',
      },
    },
    borderRadius: {
      sm: 'calc(var(--radius) - 4px)',
      md: 'calc(var(--radius) - 2px)',
      lg: 'var(--radius)',
      xl: 'calc(var(--radius) + 4px)',
      '2xl': 'calc(var(--radius) + 8px)',
      '3xl': 'calc(var(--radius) + 12px)',
    },
  },
}